### ISSUE TITLE
-fplugin-arg-instrument_attribute-include-file-list not work with Multiple files

### ISSUE THREAD

**Issue by semefly** [christophebedard/instrument-attribute-gcc-plugin#12]
-fplugin-arg-instrument_attribute-include-file-list=test/other/other_file.h,test/other/other_file3.h,
'test/other/other_file.' is instrumented;
but ‘test/other/other_file3.h’ is not instrumented;

**Comment by christophebedard** [comment]
Thanks for reporting this. I'll look into it.

**Comment by christophebedard** [comment]
I'll close this since I think this should now be fixed, but feel free to open it again if it turns out to not be working for you.
